SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `MERCKHARMONY` ;
CREATE SCHEMA IF NOT EXISTS `MERCKHARMONY` DEFAULT CHARACTER SET latin1 ;
USE `MERCKHARMONY` ;

-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`USERS` ;

CREATE  TABLE IF NOT EXISTS `MERCKHARMONY`.`USERS` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(400) NOT NULL ,
  `EMAIL` VARCHAR(45) NOT NULL ,
  `PASSWORD` VARCHAR(100) NOT NULL ,
  `ROLE` INT NOT NULL ,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT TRUE ,
  `CREATED_AT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_AT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  PRIMARY KEY (`USER_ID`) ,
  INDEX `IDX_EMAIL` (`EMAIL` ASC) ,
  UNIQUE INDEX `UN_EMAIL` (`EMAIL` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`CONDITIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`CONDITIONS` ;

CREATE  TABLE IF NOT EXISTS `MERCKHARMONY`.`CONDITIONS` (
  `CONDITION_ID` INT NOT NULL AUTO_INCREMENT ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  PRIMARY KEY (`CONDITION_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`SYMPTOMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`SYMPTOMS` ;

CREATE  TABLE IF NOT EXISTS `MERCKHARMONY`.`SYMPTOMS` (
  `SYMPTOM_ID` INT NOT NULL AUTO_INCREMENT ,
  `CONDITION_ID` INT NOT NULL ,
  `SYMPTOM_TYPE` VARCHAR(45) NOT NULL ,
  `CREATED_AT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_AT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  PRIMARY KEY (`SYMPTOM_ID`) ,
  INDEX `fk_SYMPTOMS_CONDITIONS1_idx` (`CONDITION_ID` ASC) ,
  CONSTRAINT `fk_SYMPTOMS_CONDITIONS1`
    FOREIGN KEY (`CONDITION_ID` )
    REFERENCES `MERCKHARMONY`.`CONDITIONS` (`CONDITION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`PAIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`PAIN` ;

CREATE  TABLE IF NOT EXISTS `MERCKHARMONY`.`PAIN` (
  `SYMPTOM_ID` INT NOT NULL ,
  `BODY_LOCATION` VARCHAR(100) NOT NULL ,
  `TIME_PERIOD` VARCHAR(100) NOT NULL ,
  `INTENSITY` INT NOT NULL ,
  `DURATION` INT NOT NULL ,
  `PICTURE_ID` INT NULL ,
  `COMMENT` VARCHAR(140) NULL ,
  PRIMARY KEY (`SYMPTOM_ID`) ,
  CONSTRAINT `fk_PAIN_SYMPTOMS`
    FOREIGN KEY (`SYMPTOM_ID` )
    REFERENCES `MERCKHARMONY`.`SYMPTOMS` (`SYMPTOM_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`STIFFNESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`STIFFNESS` ;

CREATE  TABLE IF NOT EXISTS `MERCKHARMONY`.`STIFFNESS` (
  `SYMPTOM_ID` INT NOT NULL ,
  `BODY_LOCATION` VARCHAR(100) NOT NULL ,
  `TIME_PERIOD` VARCHAR(100) NOT NULL ,
  `INTENSITY` INT NOT NULL ,
  `DURATION` INT NOT NULL ,
  `PICTURE_ID` INT NULL ,
  `COMMENT` VARCHAR(140) NULL ,
  PRIMARY KEY (`SYMPTOM_ID`) ,
  CONSTRAINT `fk_STIFNESS_SYMPTOMS1`
    FOREIGN KEY (`SYMPTOM_ID` )
    REFERENCES `MERCKHARMONY`.`SYMPTOMS` (`SYMPTOM_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`USERS_CONDITIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`USERS_CONDITIONS` ;

CREATE  TABLE IF NOT EXISTS `MERCKHARMONY`.`USERS_CONDITIONS` (
  `USER_ID` INT NOT NULL ,
  `CONDITION_ID` INT NOT NULL ,
  PRIMARY KEY (`USER_ID`, `CONDITION_ID`) ,
  INDEX `fk_USERS_has_CONDITIONS_CONDITIONS1_idx` (`CONDITION_ID` ASC) ,
  INDEX `fk_USERS_has_CONDITIONS_USERS1_idx` (`USER_ID` ASC) ,
  CONSTRAINT `fk_USERS_has_CONDITIONS_USERS1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `MERCKHARMONY`.`USERS` (`USER_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_has_CONDITIONS_CONDITIONS1`
    FOREIGN KEY (`CONDITION_ID` )
    REFERENCES `MERCKHARMONY`.`CONDITIONS` (`CONDITION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`FLARE_UP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`FLARE_UP` ;

CREATE  TABLE IF NOT EXISTS `MERCKHARMONY`.`FLARE_UP` (
  `SYMPTOM_ID` INT NOT NULL ,
  `TIME_PERIOD` VARCHAR(100) NOT NULL ,
  `INTENSITY` INT NOT NULL ,
  `DURATION` INT NOT NULL ,
  `COMMENT` VARCHAR(140) NULL ,
  PRIMARY KEY (`SYMPTOM_ID`) ,
  CONSTRAINT `fk_FLARE_UP_SYMPTOMS1`
    FOREIGN KEY (`SYMPTOM_ID` )
    REFERENCES `MERCKHARMONY`.`SYMPTOMS` (`SYMPTOM_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`TIMELINE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`TIMELINE` ;

CREATE  TABLE IF NOT EXISTS `MERCKHARMONY`.`TIMELINE` (
  `TIMELINE_ID` INT NOT NULL AUTO_INCREMENT ,
  `USER_ID` INT NOT NULL ,
  `SYMPTOM_ID` INT NOT NULL ,
  `DATE` DATETIME NOT NULL ,
  `DESCRIPTION` VARCHAR(45) NOT NULL ,
  `CREATED_AT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_AT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  PRIMARY KEY (`TIMELINE_ID`) ,
  INDEX `fk_TIMELINE_USERS1_idx` (`USER_ID` ASC) ,
  INDEX `fk_TIMELINE_SYMPTOMS1_idx` (`SYMPTOM_ID` ASC) ,
  CONSTRAINT `fk_TIMELINE_USERS1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `MERCKHARMONY`.`USERS` (`USER_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TIMELINE_SYMPTOMS1`
    FOREIGN KEY (`SYMPTOM_ID` )
    REFERENCES `MERCKHARMONY`.`SYMPTOMS` (`SYMPTOM_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`USERS_DEVICES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`USERS_DEVICES` ;

CREATE  TABLE IF NOT EXISTS `MERCKHARMONY`.`USERS_DEVICES` (
  `USER_DEVICE_ID` INT NOT NULL AUTO_INCREMENT ,
  `USER_ID` INT NOT NULL ,
  `DEVICE_ID` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`USER_DEVICE_ID`, `USER_ID`) ,
  INDEX `fk_USERS_DEVICES_USERS1_idx` (`USER_ID` ASC) ,
  CONSTRAINT `fk_USERS_DEVICES_USERS1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `MERCKHARMONY`.`USERS` (`USER_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`FATIGUE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`FATIGUE` ;

CREATE TABLE IF NOT EXISTS `MERCKHARMONY`.`FATIGUE` (
  `SYMPTOM_ID` INT NOT NULL,
  `TIME_PERIOD` VARCHAR(100) NOT NULL,
  `INTENSITY` INT NOT NULL,
  `COMMENT` VARCHAR(140) NULL,
  PRIMARY KEY (`SYMPTOM_ID`),
  CONSTRAINT `fk_FATIGUE_SYMPTOMS1`
    FOREIGN KEY (`SYMPTOM_ID`)
    REFERENCES `MERCKHARMONY`.`SYMPTOMS` (`SYMPTOM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`LESION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`LESION` ;

CREATE TABLE IF NOT EXISTS `MERCKHARMONY`.`LESION` (
  `SYMPTOM_ID` INT NOT NULL,
  `BODY_LOCATION` VARCHAR(100) NOT NULL,
  `TIME_PERIOD` VARCHAR(100) NOT NULL,
  `PICTURE_ID` INT NOT NULL,
  `COMMENT` VARCHAR(140) NULL,
  PRIMARY KEY (`SYMPTOM_ID`),
  CONSTRAINT `fk_LESION_SYMPTOMS1`
    FOREIGN KEY (`SYMPTOM_ID`)
    REFERENCES `MERCKHARMONY`.`SYMPTOMS` (`SYMPTOM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`BOWEL_MOVEMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`BOWEL_MOVEMENT` ;

CREATE TABLE IF NOT EXISTS `MERCKHARMONY`.`BOWEL_MOVEMENT` (
  `SYMPTOM_ID` INT NOT NULL,
  `AMOUNT` INT NOT NULL,
  `TIME_PERIOD_ABDOMINAL_PAIN` VARCHAR(100) NOT NULL,
  `TIME_PERIOD_ABDOMINAL_CRAMPS` VARCHAR(100) NOT NULL,
  `COMMENT` VARCHAR(140) NULL,
  PRIMARY KEY (`SYMPTOM_ID`),
  CONSTRAINT `fk_BOWEL_MOVEMENT_SYMPTOMS1`
    FOREIGN KEY (`SYMPTOM_ID`)
    REFERENCES `MERCKHARMONY`.`SYMPTOMS` (`SYMPTOM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`DIARRHEA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`DIARRHEA` ;

CREATE TABLE IF NOT EXISTS `MERCKHARMONY`.`DIARRHEA` (
  `SYMPTOM_ID` INT NOT NULL,
  `DIARRHEA_DURATION` INT NOT NULL,
  `DIARRHEA_ACCIDENTS` INT NOT NULL,
  `COMMENT` VARCHAR(140) NULL,
  PRIMARY KEY (`SYMPTOM_ID`),
  CONSTRAINT `fk_DIARRHEA_SYMPTOMS1`
    FOREIGN KEY (`SYMPTOM_ID`)
    REFERENCES `MERCKHARMONY`.`SYMPTOMS` (`SYMPTOM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`RECTAL_BLEEDING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`RECTAL_BLEEDING` ;

CREATE TABLE IF NOT EXISTS `MERCKHARMONY`.`RECTAL_BLEEDING` (
  `SYMPTOM_ID` INT NOT NULL,
  `TIME_PERIOD` VARCHAR(100) NOT NULL,
  `COMMENT` VARCHAR(140) NULL,
  PRIMARY KEY (`SYMPTOM_ID`),
  CONSTRAINT `fk_RECTAL_BLEEDING_SYMPTOMS1`
    FOREIGN KEY (`SYMPTOM_ID`)
    REFERENCES `MERCKHARMONY`.`SYMPTOMS` (`SYMPTOM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`PUS_IN_STOOL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`PUS_IN_STOOL` ;

CREATE TABLE IF NOT EXISTS `MERCKHARMONY`.`PUS_IN_STOOL` (
  `SYMPTOM_ID` INT NOT NULL,
  `TIME_PERIOD` VARCHAR(100) NOT NULL,
  `COMMENT` VARCHAR(140) NULL,
  PRIMARY KEY (`SYMPTOM_ID`),
  CONSTRAINT `fk_PUS_IN_STOOL_SYMPTOMS1`
    FOREIGN KEY (`SYMPTOM_ID`)
    REFERENCES `MERCKHARMONY`.`SYMPTOMS` (`SYMPTOM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERCKHARMONY`.`EYE_REDNESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MERCKHARMONY`.`EYE_REDNESS` ;

CREATE TABLE IF NOT EXISTS `MERCKHARMONY`.`EYE_REDNESS` (
  `SYMPTOM_ID` INT NOT NULL,
  `TIME_PERIOD` VARCHAR(100) NOT NULL,
  `COMMENT` VARCHAR(140) NULL,
  PRIMARY KEY (`SYMPTOM_ID`),
  CONSTRAINT `fk_EYE_REDNESS_SYMPTOMS1`
    FOREIGN KEY (`SYMPTOM_ID`)
    REFERENCES `MERCKHARMONY`.`SYMPTOMS` (`SYMPTOM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `MERCKHARMONY` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `MERCKHARMONY`.`CONDITIONS`
-- -----------------------------------------------------
START TRANSACTION;
USE `MERCKHARMONY`;
INSERT INTO `MERCKHARMONY`.`CONDITIONS` (`CONDITION_ID`, `DESCRIPTION`) VALUES (1, 'Rheumatoid Arthritis');
INSERT INTO `MERCKHARMONY`.`CONDITIONS` (`CONDITION_ID`, `DESCRIPTION`) VALUES (2, 'Ankylosing Spondylitis');
INSERT INTO `MERCKHARMONY`.`CONDITIONS` (`CONDITION_ID`, `DESCRIPTION`) VALUES (3, 'Psoriasis ');
INSERT INTO `MERCKHARMONY`.`CONDITIONS` (`CONDITION_ID`, `DESCRIPTION`) VALUES (4, 'Ulcerative Colitis & Pediatric');
INSERT INTO `MERCKHARMONY`.`CONDITIONS` (`CONDITION_ID`, `DESCRIPTION`) VALUES (5, 'Crohn’s Disease & Pediatric Crohn’s Disease');
INSERT INTO `MERCKHARMONY`.`CONDITIONS` (`CONDITION_ID`, `DESCRIPTION`) VALUES (6, 'Psoriatic Arthritis');
INSERT INTO `MERCKHARMONY`.`CONDITIONS` (`CONDITION_ID`, `DESCRIPTION`) VALUES (7, 'Juvenile Idiopathic Arthritis');

COMMIT;
